Adding Battleball.
edm00se/awesome-board-games pull request #130
Opened 2020-10-01 17:54 UTC by Quinncuatro

Submitting this PR means you have:

- [ ] searched the [readme](https://github.com/edm00se/awesome-board-games/blob/master/readme.md) file and searched the [open pull requests](https://github.com/edm00se/awesome-board-games/pulls) (no duplicates please)
- [ ] and will follow [the desired format](https://github.com/edm00se/awesome-board-games/blob/master/formatting.md)
- [ ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines](https://github.com/edm00se/awesome-board-games/blob/master/contributing.md) or [open an issue](https://github.com/edm00se/awesome-board-games/issues/new).

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

2020-10-02 13:39 UTC, edm00se requested changes
The image is too large. You can see in the file path that it's a 900x600 pixel. The target size is ~250px X 250px. If it's close, the rest looks good.

2020-10-05 19:00 UTC, Quinncuatro commented
Updated to include the smallest hosted image I could find.

Also, any chance this PR could have a "hacktoberfest-accepted" label added to it?

2020-10-05 20:12 UTC, edm00se requested changes
If you can update those links, this should be good to go. I found a couple images that should be perfect and added them as suggested changes, which should make things easy.

2020-10-05 20:12 UTC, edm00se commented on readme.md
> +![Battleball Image](https://i.ebayimg.com/images/g/xFsAAOSwOMpd6G8M/s-l400.jpg)
```suggestion
![Battleball Image](https://cf.geekdo-images.com/itemrep/img/_ybsCFVKunSnqyGPCiuXbT2kuDo=/fit-in/246x300/filters:strip_icc()/pic227687.jpg)
```

Like I mentioned in the first commit, there's a specified image size for the cdn path; finding the correct pre-generated image source means there's a more size appropriate version available to use.

2020-10-05 20:12 UTC, edm00se commented on readme.md
> +![Heroscape Master Set: Rise of the Valkyrie](https://cdn.shopify.com/s/files/1/1031/9405/products/1_13261260-646a-4892-a1ab-737aa730c902.jpeg?v=1589744301)
```suggestion
![Heroscape Master Set: Rise of the Valkyrie](https://cf.geekdo-images.com/itemrep/img/QxW14xwSXjhYU8h_KlvG09nbBd0=/fit-in/246x300/filters:strip_icc()/pic244662.jpg)
```

Similar story to this one. Normally I'd like people to keep PRs for games separate, but it's fine.

2020-10-05 23:23 UTC, edm00se commented on readme.md
> +![Battleball Image](https://i.ebayimg.com/images/g/xFsAAOSwOMpd6G8M/s-l400.jpg)
This looks good.

2020-10-05 23:27 UTC, edm00se commented on readme.md
> +![Heroscape Master Set: Rise of the Valkyrie](https://cdn.shopify.com/s/files/1/1031/9405/products/1_13261260-646a-4892-a1ab-737aa730c902.jpeg?v=1589744301)
This image hasn’t changed and its current resolution is still a bit over size (400x300), with a fair amount of white space. The suggested code change image source is 246x125 and has no extra white space in the image.

2020-10-06 14:26 UTC, edm00se approved these changes
Looks good, thanks for contributing.

2020-10-06 14:26 UTC, merged