Add The Mind
edm00se/awesome-board-games pull request #137
Opened 2020-10-20 20:52 UTC by ruthiel

Reference to #131
Thank you for the opportunity!

Submitting this PR means you have:

- [ X] searched the [readme](https://github.com/edm00se/awesome-board-games/blob/master/readme.md) file and searched the [open pull requests](https://github.com/edm00se/awesome-board-games/pulls) (no duplicates please)
- [X ] and will follow [the desired format](https://github.com/edm00se/awesome-board-games/blob/master/formatting.md)
- [X ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines](https://github.com/edm00se/awesome-board-games/blob/master/contributing.md) or [open an issue](https://github.com/edm00se/awesome-board-games/issues/new).

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

2020-10-22 21:12 UTC, edm00se requested changes
Please update the image, an alternative that meets the targeted image size has been suggested. Otherwise this PR looks good.

2020-10-22 21:12 UTC, edm00se commented on readme.md
> +![The Mind image](https://cf.geekdo-images.com/q_JGK291hrhnhiRB0667oA__imagepage/img/WUf5FT5SWkXQsf-K1Q3-fHyyJYY=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3979766.png)
```suggestion
![The Mind image](https://cf.geekdo-images.com/itemrep/img/w6x_ahGLQVe2u6trDx0kO91OprM=/fit-in/246x300/filters:strip_icc()/pic3979766.png)
```

The image is a bit larger than the recommended format size. This tile image would suit it better.

2020-10-24 00:33 UTC, edm00se approved these changes
Thanks for contributing. Happy Hacktoberfest!

2020-10-24 00:33 UTC, merged

2020-10-24 10:12 UTC, ruthiel commented
Thank you for your initiative!
Happy Hacktoberfest! =)