added Rat-a-Tat Cat game
edm00se/awesome-board-games pull request #177
Opened 2021-09-30 23:21 UTC by omriattiya

Submitting this PR means you have:

- [x] searched the [readme](https://github.com/edm00se/awesome-board-games/blob/main/readme.md) file and searched the [open pull requests](https://github.com/edm00se/awesome-board-games/pulls) (no duplicates please)
- [x] and will follow [the desired format](https://github.com/edm00se/awesome-board-games/blob/main/formatting.md)
- [x] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines](https://github.com/edm00se/awesome-board-games/blob/main/contributing.md) or [open an issue](https://github.com/edm00se/awesome-board-games/issues/new).

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

This PR is for Hacktoberfest #176

2021-09-30 23:57 UTC, edm00se requested changes
Thank you for contributing @omriattiya. The image size is a bit big. I've suggested an alternate source that should be a better match. Once that's updated I'll be happy to approve and merge this PR.

2021-09-30 23:57 UTC, edm00se commented on readme.md
> +![Rat-a-Tat Cat image](https://cf.geekdo-images.com/4nQQ9GA-1JXcxwNd-tCR8w__imagepage/img/5-81C1cMjLUJ36rrR6YuxMJILHs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic147435.jpg)
The image is oversized for what the formatting guide targets. I found an alternative source that better first the target size.

```suggestion
![Rat-a-Tat Cat image](https://cf.geekdo-images.com/4nQQ9GA-1JXcxwNd-tCR8w__itemrep/img/7bCQhZauNwAuekRT3xwbt2FCLlo=/fit-in/246x300/filters:strip_icc()/pic147435.jpg)
```

2021-10-01 00:13 UTC, omriattiya commented
@edm00se updated

2021-10-01 02:29 UTC, edm00se approved these changes
Thank you!

2021-10-01 02:29 UTC, merged