Update Readme.md
edm00se/awesome-board-games pull request #395
Opened 2023-10-18 17:12 UTC by Bratajit-03

Submitting this PR means you have:

- [x] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [x] and will follow [the desired format][format-url]
- [x] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines][contributing-url] or [open an issue][new-issue-url].

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

[pr-url]: https://github.com/edm00se/awesome-board-games/pulls
[readme-url]: https://github.com/edm00se/awesome-board-games/edit/main/readme.md
[format-url]: https://github.com/edm00se/awesome-board-games/blob/main/formatting.md
[contributing-url]: https://github.com/edm00se/awesome-board-games/blob/main/contributing.md
[new-issue-url]: https://github.com/edm00se/awesome-board-games/issues/new

2023-10-18 17:26 UTC, Bratajit-03 commented
@edm00se please kindly review my PR and merge it.

2023-10-18 21:48 UTC, edm00se requested changes
Please correct the image alt text and update the Pull Request title to be accurate.

2023-10-18 21:48 UTC, edm00se commented on readme.md
> +![Outfoxed](https://cf.geekdo-images.com/4BTVGQWO0M9ayxyku3FW6Q__itemrep/img/0hqPt1oo9J1GxmHqluUP-QC7xII=/fit-in/246x300/filters:strip_icc()/pic3477004.jpg)
The image alt text isn't accurate.

2023-10-18 22:08 UTC, Bratajit-03 commented
@edm00se sir, I have resolved the issue,please give it a check and allow it to merge.

2023-10-19 13:12 UTC, edm00se approved these changes
Thanks for contributing!

refs #269

2023-10-19 13:12 UTC, merged