added Chanakya's Chakkravyuh
edm00se/awesome-board-games pull request #396
Opened 2023-10-18 22:22 UTC by 404Nikhil

2023-10-19 05:43 UTC, 404Nikhil commented
Please check this PR @edm00se

2023-10-20 03:24 UTC, edm00se requested changes
Please update the description b lock and image source.

2023-10-20 03:24 UTC, edm00se commented on readme.md
> +The player initially chooses a dream out of various dreams listed on the board. Each dream has a purchase price listed on it. In order to win the game, the player must purchase his/her pre-selected d
These lines, as part of the description block, should also be quoted. This is what the linter rule is currently complaining about.

```suggestion
> Inspired by the 2000-year old wisdom of prominent Indian economist Chanakya, this game enlightens individuals on how to manage money and connect financial knowledge to resourceful opportunities, which are ever-present in today's changing world.
> The player initially chooses a dream out of various dreams listed on the board. Each dream has a purchase price listed on it. In order to win the game, the player must purchase his/her pre-selected dream.
```

2023-10-20 03:24 UTC, edm00se commented on readme.md
> +![Chanakya's Chakkravyuh](https://www.chanakyaschakkravyuh.com/wp-content/uploads/2016/01/LC-Box-Front-1-300x220.jpg)
Please update the image source to use one from preferably wikipedia or BGG. While the publisher may be an authoritative source, there's no guarantee their wordpress site uses an image cdn, unlike the other two mentioned.

2023-10-20 05:11 UTC, 404Nikhil commented
Hello @edm00se so I have fixed the cause of linting error and about the image source in BGM it's was not allowing me to resize the image size in URL itself and there's no existing Wikipedia page for it. So I decided to simply download one put the images in assets folder and link the relative path. It's previewing fine. Hopefully no error come up this time.

2023-10-20 15:54 UTC, edm00se commented
I'd love to not need to host the image,  but a quick search led me to the same conclusion. I'll have another look this evening when I have a few minutes and see if I can find another that will do what I'd like first.

2023-10-21 10:50 UTC, closed without merging