Added Diplomacy Game
edm00se/awesome-board-games pull request #411
Opened 2023-10-21 05:40 UTC by chinmay7016

#269 

Submitting this PR means you have:

- [ ] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [ ] and will follow [the desired format][format-url]
- [ ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines][contributing-url] or [open an issue][new-issue-url].

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

[pr-url]: https://github.com/edm00se/awesome-board-games/pulls
[readme-url]: https://github.com/edm00se/awesome-board-games/edit/main/readme.md
[format-url]: https://github.com/edm00se/awesome-board-games/blob/main/formatting.md
[contributing-url]: https://github.com/edm00se/awesome-board-games/blob/main/contributing.md
[new-issue-url]: https://github.com/edm00se/awesome-board-games/issues/new

2023-10-21 13:53 UTC, chinmay7016 commented
@edm00se if you like this changes pls merge this pr

2023-10-22 13:06 UTC, edm00se requested changes
The content changes look good, but to get this merged we’ll need:
- an update to the description block markdown formatting
- to move the addition above the “contribute” section, preferably to the strategy section of the document

2023-10-22 13:06 UTC, edm00se commented on readme.md
> +The first The Avalon Hill Game Co version has perhaps the widest release, but Avalon Hill re-released the game in 1999, complete with a colorful new map and metal pieces. In 2008, Avalon Hill release
Please format the rest of the description block, they’ll need the leading `> ` for each line.

2023-10-22 13:06 UTC, edm00se commented on readme.md
> +
If you look up a line or two, you can see the addition went too low, below the “contribute” paragraph. Please move your addition above this, preferably to one of the sections that makes sense, like “strategy”.

2023-10-22 13:24 UTC, chinmay7016 reviewed
sir pls see the updated file

2023-10-22 13:43 UTC, chinmay7016 commented
@edm00se  sir pls review changes and merge it pls sir.

2023-10-22 15:07 UTC, edm00se commented on readme.md
> +The first The Avalon Hill Game Co version has perhaps the widest release, but Avalon Hill re-released the game in 1999, complete with a colorful new map and metal pieces. In 2008, Avalon Hill release
I see the entry got moved, the only thing I see now is that both other paragraphs for the description needs to be formatted with the leading `>`.

2023-10-22 15:08 UTC, edm00se commented
I see the entry got moved, the only thing I see now is that both other paragraphs for the description needs to be formatted with the leading `>`.

2023-10-22 15:24 UTC, chinmay7016 commented
@edm00se sir pls review changes and merge it pls sir.

2023-10-22 16:46 UTC, edm00se approved these changes

2023-10-22 16:47 UTC, merged