Added Amerigo game
edm00se/awesome-board-games pull request #412
Opened 2023-10-21 05:52 UTC by chinmay7016

#269

Submitting this PR means you have:

- [ ] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [ ] and will follow [the desired format][format-url]
- [ ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines][contributing-url] or [open an issue][new-issue-url].

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

[pr-url]: https://github.com/edm00se/awesome-board-games/pulls
[readme-url]: https://github.com/edm00se/awesome-board-games/edit/main/readme.md
[format-url]: https://github.com/edm00se/awesome-board-games/blob/main/formatting.md
[contributing-url]: https://github.com/edm00se/awesome-board-games/blob/main/contributing.md
[new-issue-url]: https://github.com/edm00se/awesome-board-games/issues/new

2023-10-21 13:53 UTC, chinmay7016 commented
@edm00se if you like this changes pls merge this pr

2023-10-22 13:11 UTC, edm00se requested changes
Please update the description block formatting.

2023-10-22 13:11 UTC, edm00se commented on readme.md
> +The actions available to players are determined through the use of a specialized cube tower, which has appeared in the Queen titles Im Zeichen des Kreuzes and Wallenstein. At the start of the game, t
We’ll need another update to the description block here.

2023-10-22 13:44 UTC, chinmay7016 commented
@edm00se  sir pls review changes and merge it pls sir.

2023-10-22 15:27 UTC, chinmay7016 commented
@edm00se sir pls review changes and merge it pls sir.

2023-10-22 16:44 UTC, edm00se approved these changes

2023-10-22 16:45 UTC, merged