Added Lords of Vegas
edm00se/awesome-board-games pull request #413
Opened 2023-10-21 06:05 UTC by chinmay7016

#269 
Submitting this PR means you have:

- [ ] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [ ] and will follow [the desired format][format-url]
- [ ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines][contributing-url] or [open an issue][new-issue-url].

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

[pr-url]: https://github.com/edm00se/awesome-board-games/pulls
[readme-url]: https://github.com/edm00se/awesome-board-games/edit/main/readme.md
[format-url]: https://github.com/edm00se/awesome-board-games/blob/main/formatting.md
[contributing-url]: https://github.com/edm00se/awesome-board-games/blob/main/contributing.md
[new-issue-url]: https://github.com/edm00se/awesome-board-games/issues/new

2023-10-21 13:53 UTC, chinmay7016 commented
@edm00se if you like this changes pls merge this pr

2023-10-22 13:13 UTC, edm00se requested changes
Looks like the description block formatting is needed here as well. Also please remove the ~”this game has…” list. Everything else looks good.

2023-10-22 13:13 UTC, edm00se commented on readme.md
> +The game board is broken into 6 different areas, each consisting of a number of empty 'lots'. Players build lots by paying money and placing a die of the value matching the one shown on the lot's spa
Please update the formatting here as well.

2023-10-22 13:13 UTC, edm00se commented on readme.md
> +Lords of Vegas contains:
This list can be removed.

2023-10-22 13:44 UTC, chinmay7016 commented
@edm00se  sir pls review changes and merge it pls sir.

2023-10-22 15:29 UTC, chinmay7016 commented
@edm00se sir pls review changes and merge it pls sir.

2023-10-22 16:49 UTC, edm00se approved these changes

2023-10-22 16:51 UTC, merged