Added Zombie Kidz Evolution
edm00se/awesome-board-games pull request #414
Opened 2023-10-21 06:12 UTC by chinmay7016

#269 
Submitting this PR means you have:

- [ ] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [ ] and will follow [the desired format][format-url]
- [ ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines][contributing-url] or [open an issue][new-issue-url].

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

[pr-url]: https://github.com/edm00se/awesome-board-games/pulls
[readme-url]: https://github.com/edm00se/awesome-board-games/edit/main/readme.md
[format-url]: https://github.com/edm00se/awesome-board-games/blob/main/formatting.md
[contributing-url]: https://github.com/edm00se/awesome-board-games/blob/main/contributing.md
[new-issue-url]: https://github.com/edm00se/awesome-board-games/issues/new

2023-10-21 13:52 UTC, chinmay7016 commented
@edm00se if you like this changes pls merge this pr

2023-10-22 13:17 UTC, edm00se requested changes
Description block formatting and the title needs to be fixed.

2023-10-22 13:17 UTC, edm00se commented on readme.md
> +### [zombie-kidz-evolution](https://boardgamegeek.com/boardgame/256952/zombie-kidz-evolution)
Please fix the title.

2023-10-22 13:17 UTC, edm00se commented on readme.md
> +In the game, the young players are at school when zombies start to attack, infiltrating the entryways, then barring the way to classrooms. Players move through rooms and entryways to eliminate zombie
Please update the description block formatting here as well.

2023-10-22 13:44 UTC, chinmay7016 commented
@edm00se  sir pls review changes and merge it pls sir.

2023-10-22 16:54 UTC, edm00se commented on readme.md
> +### [zombie kidz evolution](https://boardgamegeek.com/boardgame/256952/zombie-kidz-evolution)
The title should be cased correctly.

```suggestion
### [Zombie Kidz Evolution](https://boardgamegeek.com/boardgame/256952/zombie-kidz-evolution)
```

2023-10-22 16:54 UTC, edm00se approved these changes

2023-10-22 16:56 UTC, merged