Added Civilization game
edm00se/awesome-board-games pull request #416
Opened 2023-10-21 06:54 UTC by chinmay7016

#269 
Submitting this PR means you have:

- [ ] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [ ] and will follow [the desired format][format-url]
- [ ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines][contributing-url] or [open an issue][new-issue-url].

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

[pr-url]: https://github.com/edm00se/awesome-board-games/pulls
[readme-url]: https://github.com/edm00se/awesome-board-games/edit/main/readme.md
[format-url]: https://github.com/edm00se/awesome-board-games/blob/main/formatting.md
[contributing-url]: https://github.com/edm00se/awesome-board-games/blob/main/contributing.md
[new-issue-url]: https://github.com/edm00se/awesome-board-games/issues/new

2023-10-21 13:52 UTC, chinmay7016 commented
@edm00se if you like this changes pls merge this pr

2023-10-22 13:23 UTC, edm00se requested changes
The description block needs a formatting update.

2023-10-22 13:23 UTC, edm00se commented on readme.md
> +Yet a dark shadow grows in the city of Arkham. Alien entities known as Ancient Ones lurk in the emptiness beyond space and time, writhing at the gates between worlds. These gates have begun to open a
This line of the description block also needs the markdown formatting update.

```suggestion
> Yet a dark shadow grows in the city of Arkham. Alien entities known as Ancient Ones lurk in the emptiness beyond space and time, writhing at the gates between worlds. These gates have begun to open and must be closed before the Ancient Ones make our world their ruined domination.
```

2023-10-22 13:54 UTC, chinmay7016 commented
@edm00se sir pls review changes and merge it pls sir.

2023-10-22 16:57 UTC, edm00se approved these changes
I’m surprised this wasn’t added previously.

2023-10-22 16:58 UTC, merged