Added game - Shadow of Brimstone.
edm00se/awesome-board-games pull request #438
Opened 2023-10-23 18:44 UTC by Kris248

Submitting this PR means you have:

- [ ] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [ ] and will follow [the desired format][format-url]
- [ ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS
- [ ] read [this year's Hacktoberfest welcome issue](https://github.com/edm00se/awesome-board-games/issues/269)
- [ ] promised not to `@` me asking for review (I will see the notifications already, no need to add noise)

Once your PR is created, it will trigger a build a couple of automated checks, including a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them. The others include a check on the submission limit and also a preview of the site with your changes; please check them out, they are tools tonhelp us both.

Do you have further questions? Check the [contribution guidelines][contributing-url] or [open an issue][new-issue-url].

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

[pr-url]: https://github.com/edm00se/awesome-board-games/pulls
[readme-url]: https://github.com/edm00se/awesome-board-games/edit/main/readme.md
[format-url]: https://github.com/edm00se/awesome-board-games/blob/main/formatting.md
[contributing-url]: https://github.com/edm00se/awesome-board-games/blob/main/contributing.md
[new-issue-url]: https://github.com/edm00se/awesome-board-games/issues/new

2023-10-25 18:26 UTC, edm00se requested changes
There are a few things to fix, but most of that is formatting except for the extra file that should be removed.

2023-10-25 18:26 UTC, edm00se commented on .gitpod.yml
This file should not be here.

2023-10-25 18:26 UTC, edm00se commented on readme.md
> +### [Shadows of Brimstone: Swamps of Death (2014)](https://boardgamegeek.com/boardgame/15099shadows-brimstone-swamps-death)
The link is malformed. Also yremove the year from the end of the title.

2023-10-25 18:26 UTC, edm00se commented on readme.md
> +Can be used together with Shadows of Brimstone: City of the Ancients to raise the maximum players to 6.
The entirety of the description block needs to be commented, lines start with the `> ` character and a space.

2023-10-26 06:55 UTC, Kris248 commented
Can u review? Like this you want?

2023-10-26 19:40 UTC, edm00se approved these changes
Thanks for contributing!

refs #269

2023-10-26 19:40 UTC, merged

2023-10-26 19:43 UTC, Kris248 commented
i just added 1 game only. Can i add 10-20 games also like previous one?